package lab06;
import javax.swing.DefaultListModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class GestorCursos extends javax.swing.JFrame {
    //Creamos el modelo y la lista
    DefaultListModel modeloCursos = new DefaultListModel();
    List<CURSO> listaCursos = new ArrayList<>();

    public GestorCursos() {
        initComponents();
        ActualizarModelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtBuscarCursos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarCurso = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        lblbtnProfesores = new javax.swing.JLabel();
        lblbtnEstudiantes = new javax.swing.JLabel();
        btnEliminarCurso = new javax.swing.JLabel();
        btnAgregarCurso = new javax.swing.JLabel();
        seguro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(131, 165, 215));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PRINCIPAL/TituloP.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(131, 165, 215));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarCursos.setBorder(null);
        jPanel5.add(txtBuscarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PRINCIPAL/Rectangle 2.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        btnBuscarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PRINCIPAL/BUSCAR.png"))); // NOI18N
        btnBuscarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCursoMouseClicked(evt);
            }
        });

        jList4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jList4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(jList4);

        lblbtnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PRINCIPAL/PROFESORES.png"))); // NOI18N
        lblbtnProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbtnProfesoresMouseClicked(evt);
            }
        });

        lblbtnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PRINCIPAL/ESTUDIANTES.png"))); // NOI18N
        lblbtnEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbtnEstudiantesMouseClicked(evt);
            }
        });

        btnEliminarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PRINCIPAL/ELIMINAR.png"))); // NOI18N
        btnEliminarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCursoMouseClicked(evt);
            }
        });

        btnAgregarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PRINCIPAL/AGREGAR.png"))); // NOI18N
        btnAgregarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCursoMouseClicked(evt);
            }
        });

        seguro.setText("jTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(seguro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarCurso))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblbtnProfesores)
                        .addGap(18, 18, 18)
                        .addComponent(lblbtnEstudiantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCurso)))
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(seguro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblbtnProfesores)
                    .addComponent(lblbtnEstudiantes)
                    .addComponent(btnAgregarCurso)
                    .addComponent(btnEliminarCurso))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAgregarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCursoMouseClicked
        //Para agregar un curso
        //Abrimos la nueva pantalla para que meta los datos
        VENT_A_CURSO ven = new VENT_A_CURSO(this);
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_btnAgregarCursoMouseClicked

    private void lblbtnProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtnProfesoresMouseClicked
        //Abrimos la nueva pantalla para que meta los datos de los profesores
        //Solo se abre si esta seleccionado algo del la lista
        if(BuscarIndiceActual() == -1){
            //No hacemos nada
        }else{
            VENT_PROFESORES ven = new VENT_PROFESORES(this);
            ven.CambiarTitulo(
                    listaCursos.get(BuscarIndiceActual()).getNombre());
            ven.setVisible(true);
            ven.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_lblbtnProfesoresMouseClicked

    private void lblbtnEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtnEstudiantesMouseClicked
        if(BuscarIndiceActual() == -1){
            //No hacemos nada
        }
        else{
            VENT_ESTUDIANTES ven = new VENT_ESTUDIANTES(this);
            ven.CambiarTitulo(
                    listaCursos.get(BuscarIndiceActual()).getNombre());
            ven.setVisible(true);
            ven.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_lblbtnEstudiantesMouseClicked

    private void btnEliminarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCursoMouseClicked
        // Eliminamos 
        if(BuscarIndiceActual() == -1){
            //No hacemos nada
        }
        else{
            //Eliminamos
            listaCursos.remove(BuscarIndiceActual());
            ActualizarModelo();
        }
        
    }//GEN-LAST:event_btnEliminarCursoMouseClicked

    private void btnBuscarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCursoMouseClicked
        // Boton buscar
        if(txtBuscarCursos.getText().equals("")){
            //NO hacemos nada
        }else{
            //Vamos a buscar el string en la lista actual de Estudiante
            String palabra = txtBuscarCursos.getText();
            int flag = 0;
            for( int i = 0; i< listaCursos.size();i++){
                if(listaCursos.get(i).getCodigo().equals(palabra)){
                    //Mostramos que si esta encontrado
                    flag = 1;
                    //Mostramos mensaje
                    JOptionPane.showMessageDialog(null, ""
                            + "El Curso SI fue encontrado");
                }
            }
            if(flag == 0){
                JOptionPane.showMessageDialog(null, ""
                        + "El Curso NO fue encontrado");
            }
        }
    }//GEN-LAST:event_btnBuscarCursoMouseClicked

   
    //METODO PARA ACTUALIZAR METODO
    //public void ActualizarModelo(DefaultListModel model){
    //    this.jList4.setModel(model);
    //}
    public final void ActualizarModelo(){
        this.modeloCursos = new DefaultListModel();
        for (int i = 0; i < listaCursos.size(); i++) {
            String text = listaCursos.get(i).getTEXTO_C();
            this.modeloCursos.addElement(text);
        }
        this.jList4.setModel(modeloCursos);
    }
    
    
                                      //listadeProfesores, indicedelcursoAactualizar
    public void ActualizarProfesoresdelCurso(List<PROFESOR> lista_, int index){
        //Buscamos el curso
        listaCursos.get(index).setProfesores(lista_);
    }
    
    public int BuscarIndiceActual(){
        int index = jList4.getSelectedIndex();
        return index;
    }
    //Aqui agrega metodos para abrir las ventanas de cada boton
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregarCurso;
    private javax.swing.JLabel btnBuscarCurso;
    private javax.swing.JLabel btnEliminarCurso;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblbtnEstudiantes;
    private javax.swing.JLabel lblbtnProfesores;
    private javax.swing.JTextField seguro;
    private javax.swing.JTextField txtBuscarCursos;
    // End of variables declaration//GEN-END:variables
}
